### ISSUE TITLE
Camera Zoom => blur bug

### ISSUE THREAD

**Issue by Kuranes** [hoverinc/ray-tracing-renderer#35] opened 2019-10-24 16:46 UTC
When you zoom it all becomes blurry (including the env)
repro on https://hover-demos.s3.amazonaws.com/ray-tracing-renderer/readme-example/index.html, zoom a lot and turn camera to look at the env

![image](https://user-images.githubusercontent.com/128571/67507137-a2e1b280-f68e-11e9-8489-a7854ff23c54.png)
(that's after long render time )

Camera ends behind the helmet in the box looking at "outside"

( chrome 78, windows nvidia gpu)

possibly 
- camera focus DOF problem
- sample for SSAA/TAA too big

**Comment by jaxry** [comment] 2019-10-24 20:21
Thanks for the ticket. I believe what you're noticing is the depth-of-field produced by the [LensCamera ](https://github.com/hoverinc/ray-tracing-renderer/wiki/LensCamera) used that example.


![LENS_EM-M3035_Adriana_Vedula_Holubova_P4090475__Sample-1](https://user-images.githubusercontent.com/4411068/67521749-50899d00-f660-11e9-8bc2-323a2b12f7f0.jpg)
You'll see the same effect in zoomed-in photographs too.

That camera has a focal point and depth of field. Anything too far before or past the focal point will be blurry. If you zoom in, the focal point becomes really close to the camera, and blurring of the infinitely-distant env map will occur. You should pan the camera so that the focal point is directly on what you'd like to look at, so at least that will be in focus. Alternatively, if you're programming your own example, you could decrease the aperture of the LensCamera. That will decrease blurring with respect to distance.

**Comment by Kuranes** [comment] 2019-10-25 05:09
Thanks for the answer, 


I did implement myself lot of DOF shader, and can assure current behaviour is a bug, no DOF normal working.

Central point is blurry here and blur step are WAY to big, which never happen with dof...

Please try to repro as I posted.
Here's another repro is to load an object far from camera at first,

1.- you get env and object ok.
![image](https://user-images.githubusercontent.com/128571/67544525-1074f980-f6f6-11e9-9ced-7d68b3aba168.png)

2. then zoom => you gent Env and object Blurry. even with object centered.
![image](https://user-images.githubusercontent.com/128571/67544512-06eb9180-f6f6-11e9-8f88-b284b58ebbb7.png)

**Comment by jaxry** [comment] 2019-10-25 05:49
I'm following your steps, but I'm not able to reproduce anything I recognize as a bug. I am noticing the effects of aperture and focal point, though, which is working as intended. Does this address your concern:

The `focus` property on `LensCamera` needs to be set to the distance between the camera and whatever it is you'd like to be in focus. In the demo scene you're testing, the `focus` property is updated automatically when you pan the camera (right mouse button). So you should pan the camera so that the center of the camera's orbit controls lie on whatever you want to focus.

With the camera panned (via right clicking) to the correct spot, it works in a pleasing way
Zoomed out:
![1](https://user-images.githubusercontent.com/4411068/67545809-5c508000-f6af-11e9-834f-a0302d734217.PNG)
Zoomed in:
![2](https://user-images.githubusercontent.com/4411068/67545815-62def780-f6af-11e9-827c-ab5d64bdec63.PNG)

But if you pan the camera so that the center is at the entrance of the box, the object will be blurry because it's too far away from the focal point:
![3](https://user-images.githubusercontent.com/4411068/67545836-79854e80-f6af-11e9-98b9-068fe4404f14.PNG)

Likewise, if you pan the camera so that the focal point is at the end of the box, the object will be closer than the focal point and will be blurry.
![4](https://user-images.githubusercontent.com/4411068/67545855-886c0100-f6af-11e9-9d00-b5c568915bce.PNG)

Try panning the camera with right click. Is the bug still there?

The sketchfab demo you shared has different controls. The camera still has a center point that it orbits around, but if you zoom in enough, the camera starts panning instead of zooming. That's different from what our demo is doing (and it's probably more intuitive. I might update our demo to behave the same). But for now, does moving the camera around via right-clicking address the problem?

Also, if there's too much blurring outside the focal point, even when you're in focus, you can increase the DOF by decreasing the `aperture`.

**Comment by Kuranes** [comment] 2019-10-25 06:22
bug is still here
https://i.imgur.com/LVHMhkt.gifv

**Comment by Kuranes** [comment] 2019-10-25 06:26
on https://hover-demos.s3.amazonaws.com/ray-tracing-renderer/readme-example/index.html can you zoom and read the text on the gold plaque ?

**Comment by Kuranes** [comment] 2019-10-25 06:30
And here just zooming in object, no panning https://i.imgur.com/BiHF6wz.gifv

**Comment by jaxry** [comment] 2019-10-25 06:32
>bug is still here, made a video of it so you see the "big big blur step"

Could you rotate the camera around in a circle so I can see where the focus point is? Also that model looks much smaller than the demo model, so you probably need to lower the aperture to match the smaller scale.

Just by rotating the camera, no.
![1](https://user-images.githubusercontent.com/4411068/67548260-3d092100-f6b6-11e9-8103-852b335d2793.PNG)

But if I pan the camera to the plaque, then zoom in, it works.
![2](https://user-images.githubusercontent.com/4411068/67548275-485c4c80-f6b6-11e9-8294-9fd5e8c224f7.PNG)

**Comment by Kuranes** [comment] 2019-10-25 06:35
interesting, seems we don't have same results then
![image](https://user-images.githubusercontent.com/128571/67548467-30aab580-f702-11e9-9147-5845fa71af0d.png)

Panning does nothing at all for focus here it seems.
Do you get the blur when you zoom without panning ?

**Comment by Kuranes** [comment] 2019-10-25 06:37
> to lower the aperture 
Idea is to load any kind of model, so it has to be done programmatically.
( Also need to fit object to camera or camera to object too at load )

**Comment by jaxry** [comment] 2019-10-25 06:49
https://i.imgur.com/PjfcBdC.mp4
With the current controls in the demo scene, panning is sort of tricky. If you pan and zoom like I am in this video, does it work then?

>I'll try to update focus too programmatically then
Yeah, you should be able to implement any control system you want (like the sketchfab examplet). The renderer is unassuming in that regard.

**Comment by Kuranes** [comment] 2019-10-25 07:36
ok, tried exact same thing as the video got finally what you mean, you play with pan until you get the orbit center on the point you want to focus on.
Not easy indeed :)
Thanks for the video

Sketchfab way of controls avoid those kind of things.
It's uses mouse click + depth as way to determine focus, and when you double click you change the rotation point. which allow quick rotation change without "panning + rotation" process

**Closed** 2019-10-25 10:14 UTC
